#!/bin/bash
MB="MB"
for (( i=128; i<=8192; i=$i*2 )) do
  for (( j=1; j<=10; j++ )) do
    sysbench fileio --file-total-size="$i$MB" prepare >> /dev/null
    sysbench fileio --file-total-size="$i$MB" --file-test-mode=rndrw \
      --time=300 --max-requests=0 run >> "fileiologs/Fileio$i$MB.test"
    sysbench fileio --file-total-size="$i$MB" cleanup >> /dev/null
  done
done
